### PR TITLE
fix(app-types): Fix "dependency" typo

### LINKED ISSUE #9787: `@firebase/app-types` fails with pnpm strict mode — `dependency` field typo causes missing `@firebase/logger`
`@firebase/app-types@0.9.3` imports `@firebase/logger` in its type declarations (`index.d.ts`):

```ts
import { LogCallback, LogLevelString, LogOptions } from '@firebase/logger';
```

However, the `package.json` declares this under a `"dependency"` field (singular) instead of the correct `"dependencies"` (plural):

```json
"dependency": {
  "@firebase/logger": "0.2.6"
}
```

Package managers ignore the misspelled field, so `@firebase/logger` is never resolved as a dependency. This works in flat `node_modules` layouts (npm, yarn) because `@firebase/logger` is hoisted from other `@firebase/*` packages in the tree. When pnpm hoisting is disabled (`hoist: false`), this fails with:

```
error TS2307: Cannot find module '@firebase/logger' or its corresponding type declarations.
```

**Workaround:**
```yaml
packageExtensions:
  "@firebase/app-types@0":
    peerDependencies:
      "@firebase/logger": "*"
```

**Suggested fix:** Rename the `"dependency"` field to `"dependencies"` in `@firebase/app-types`'s `package.json`.

### PR DESCRIPTION
**Pull request by hsubox76**
Typo introduced in https://github.com/firebase/firebase-js-sdk/pull/5144 causes errors in package installers.

Fixes #9787

### CODE REVIEW

**Review by DellaBitta — APPROVED** [review]

**Comment by baraknaveh** [comment]
Thanks for the fix!
