### ISSUE TITLE
firebaseApp.firestore is not a function after upgrading to 8.1.1 from 7.24.0

### ISSUE THREAD

**Issue by Zimmerr** [firebase/firebase-js-sdk#4108]
### Describe your environment

  * Operating System version: Ubuntu 20.04
  * Browser version: Firefox 83.0
  * Firebase SDK version: 8.1.1
  * Firebase Product: Firestore

### Describe the problem
After upgrading to version 8 because i want to use Firestore Emulator, im not able to initialize the firestore properly anymore using .firestore(). The following error is given: firebaseApp.firestore is not a function

#### Steps to reproduce:
Trying to initialize the Firestore after doing firebase.initializeApp()

#### Relevant Code:

```javascript
import firebase from 'firebase/app'

import firebaseConfig from './firebaseConfig'
const firebaseApp = firebase.initializeApp(firebaseConfig)

var db = firebaseApp.firestore()

if (process.env.NODE_ENV == "development" || "testing") {
    firebase.auth().useEmulator('http://localhost:9099/');
    db.useEmulator("localhost", 4040);
}
export default db
```

**Comment by thebrianchen** [comment]
@Zimmerr Thanks for filing an issue with your question! If you're using firestore in your app, you'll also have to import 'firebase/firestore' as well. Adding the line `import "firebase/firestore"` to your code should fix the issue. 

I'm marking this issue as closed, but feel free to ask any other questions you may have!

**Comment by Zimmerr** [comment]
I tried doing this before with no effect, tried again and still get the same error (Uncaught TypeError: firebaseApp.firestore is not a function). Code now looks as the following:

```javascript
import firebase from 'firebase/app'
import "firebase/firestore"
import firebaseConfig from './firebaseConfig'
const firebaseApp = firebase.initializeApp(firebaseConfig)

var db = firebaseApp.firestore()

if (process.env.NODE_ENV == "development" || "testing") {
    firebase.auth().useEmulator('http://localhost:9099/');
    db.useEmulator("localhost", 4040);
}
export default db

```

**Comment by thebrianchen** [comment]
@Zimmerr Could you upload your code into a github repo that I can reproduce on my end?

**Comment by Zimmerr** [comment]
https://github.com/pierodesenzi/stories/tree/Firebase8

Master still runningfirebase sdk at 7 with everything working, the branch i linked on is updated to version 8 but broken and with the code i mentioned before

**Comment by thebrianchen** [comment]
@Zimmerr Thanks for the repro! I was able to fix your error with with the following steps:

1. Remove your `node_modules` directory and your `package-lock.json` file.
2. Run `npm cache clean`.
3. Run `npm install again`. 
4. Add the following code snippet to `firebaseInit.js`:
```
import firebase from 'firebase/app';
import 'firebase/firestore';
import 'firebase/auth';
```

Your `@firebase/rules-unit-testing@1.0.4` dependency had a dependency on `firebase@7.21.1`, which was locked into your `package-lock.json` file. I'm not sure why npm isn't able to load the correct dependency though. I tried updating your rules-unit-testing to 1.1.3, but the only fix that worked for me was to remove your `package-lock.json` and `node_modules` and reinstalling. Hope that helps!
