### ISSUE TITLE
TypeScript compilation error with Firebase 5.9.0

### ISSUE THREAD

**Issue by gigcompany** [firebase/firebase-js-sdk#3907]
I am enhancing an Ionic-Angular 3.9.2 PWA app that uses Firebase. I am trying to add Apple Signin as a feature into this app. I am following the approach for the integration as documented here: https://firebase.google.com/docs/auth/web/apple.
My project also uses AngularFire2.

In order to support the  Apple signing I upgraded Firebase web SDK from 4.8.0 to 5.9.0 and have upgraded AngularFire2 from 5.0.0-rc.4 to 5.0.0-rc.6. 

While trying to run the project (with ionic serve) I get the following Typescript error

typescript: src/providers/authenticata/authenticata.ts, line: 266 
            Expected 0 arguments, but got 1. 

     L265:  return new Promise((resolve, reject) => {
     L266:    var provider = new firebase.auth.OAuthProvider("apple.com");

When I check the definition of the OAuthProvider I do see that it has a property called providerId that is takes. 

`  class OAuthProvider implements firebase.auth.AuthProvider {
    providerId: string;
    /**
     * @param {string} scope Provider OAuth scope to add.
     */
    addScope(scope: string): firebase.auth.AuthProvider;`

Incidentally I noticed that If I ignore this error, add a comment in the file and save to compile again and reload the app, it works without throwing an error. 

While trying to a do a build for deployment the Angular AOT compiler again throws this issue.

[15:11:16]  typescript: src/providers/authenticata/authenticata.ts, line: 266 
            Expected 0 arguments, but got 1. 

     L265:  return new Promise((resolve, reject) => {
     L266:    var provider = new firebase.auth.OAuthProvider("apple.com");

Error: The Angular AoT build failed. See the issues above.

Here is my package.json
`{
    "name": "myapp",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve",
        "pwa": "ionic-app-scripts build --prod --platform browser && gulp build-sw",
        "browser": "ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"
    },
    "dependencies": {
        "@agm/core": "1.0.0-beta.2",
        "@angular/common": "5.0.3",
        "@angular/compiler": "5.0.3",
        "@angular/compiler-cli": "5.0.3",
        "@angular/core": "5.0.3",
        "@angular/forms": "5.0.3",
        "@angular/http": "5.0.3",
        "@angular/platform-browser": "5.0.3",
        "@angular/platform-browser-dynamic": "5.0.3",
        "@ionic-native/core": "4.4.0",
        "@ionic-native/date-picker": "4.5.2",
        "@ionic-native/firebase": "4.5.3",
        "@ionic-native/splash-screen": "4.4.0",
        "@ionic-native/status-bar": "4.20.0",
        "@ionic/storage": "2.1.3",
        "@types/intro.js": "2.4.5",
        "@types/moment": "2.13.0",
        "@types/underscore": "1.8.7",
        "angularfire2": "^5.0.0-rc.6",
        "clipboard": "2.0.1",
        "cordova-ios": "5.0.0",
        "device": "0.3.9",
        "es6-promise-plugin": "4.2.2",
        "firebase": "^5.9.0",
        "ics": "2.13.1",
        "ics-js": "0.10.2",
        "immutable-ics": "0.4.0",
        "ionic-angular": "3.9.9",
        "ionic-img-viewer": "2.9.0",
        "ionic-plugin-deeplinks": "1.0.20",
        "ionic-plugin-keyboard": "2.2.1",
        "ionic2-auto-complete": "1.6.2-alpha",
        "ionicons": "3.0.0",
        "moment": "2.20.1",
        "ng-lottie": "0.3.2",
        "node-sass": "4.6.0",
        "promise-polyfill": "7.0.2",
        "rxjs": "5.5.2",
        "underscore": "1.8.3",
        "workbox-sw": "3.1.0",
        "ws": "3.3.2",
        "xcode": "2.0.0",
        "zone.js": "0.8.18"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.2.3",
        "@types/googlemaps": "3.36.5",
        "typescript": "2.4.2",
        "workbox-build": "4.3.1"
    },
    "description": "An Ionic project",
    "config": {
        "ionic_copy": "./config/copy.config.js"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-datepicker": {},
            "cordova-plugin-device": {},
        },
        "platforms": [
            "browser"
        ]
    }
}
`
My code is as below
`import { AngularFireDatabase } from "angularfire2/database";
import * as firebase from "firebase/app";
..
..
  async signInWithApple() {
    return new Promise((resolve, reject) => {
      var provider = new firebase.auth.OAuthProvider("apple.com");
      firebase
        .auth()
      .signInWithPopup(provider)
      .then((result) => {
// I handle the firebase auth and other logic here
})
...

`

My environment and CLI versions are as below : 

username$ ionic info

cli packages: (/Users/gofloaters/.nvm/versions/node/v8.13.0/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : android 8.1.0 browser 6.0.0 ios 5.0.0
    Ionic Framework    : ionic-angular 3.9.9

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.4 
    Node              : v8.13.0
    npm               : 6.4.1 
    OS                : macOS
    Xcode             : Xcode 11.2.1 Build version 11B500 

Please help.

**Comment by hsubox76** [comment]
Can I ask why you chose Firebase version 5.9.0? Apple sign-in support wasn't introduced until version 7.4.0 and the most recent version is 7.22.1.

**Comment by gigcompany** [comment]
> Can I ask why you chose Firebase version 5.9.0? Apple sign-in support wasn't introduced until version 7.4.0 and the most recent version is 7.22.1.

This app was using a very old version of firebase prior (which is 4.8.0). Hence I wanted to upgrade only to the next version where I can make the Apple Signin work and not jump multiple major versions as that might have introduced a lot of breaking changes. 

I was able to get Apple Signin to work with this version of firebase 5.9.0 by using the generic OAuthProvider, but I am facing compilation issues when trying to create a build.

**Comment by hsubox76** [comment]
In terms of bugs and feature requests, we only support the latest version and any fixes in response to an issue would go into subsequent versions. If there was a bug to be fixed, we would fix it in the latest version and wouldn't roll the fix back to 5.x.x so if you're set on using 5.9.0, you may want to ask for help through Firebase Support or on Stack Overflow.

If you ever are able to upgrade to the latest version and find the same error, please let us know.

**Comment by Feiyang1** [comment]
@gigcompany Can you upgrade to 5.9.4 where the constructor parameter was added?

**Comment by gigcompany** [comment]
> @gigcompany Can you upgrade to 5.9.4 where the constructor parameter was added?

When I upgrade to 5.9.4 and run the code I get the following error.

`Uncaught Error: Cannot find module "core-js/features/array/find"
    at Object.<anonymous> (index.esm.js:1)
    at __webpack_require__ (bootstrap 3108ccac3feeacc9cc95:54)
    at Object.<anonymous> (index.cjs.js:5)
    at __webpack_require__ (bootstrap 3108ccac3feeacc9cc95:54)
    at Object.100 (main.js:14)
    at __webpack_require__ (bootstrap 3108ccac3feeacc9cc95:54)
    at Object.549 (main.ts:9)
    at __webpack_require__ (bootstrap 3108ccac3feeacc9cc95:54)
    at Object.544 (main.ts:1)
    at __webpack_require__ (bootstrap 3108ccac3feeacc9cc95:54)`

**Comment by Feiyang1** [comment]
Can you try to do a clean install? If it still doesn't work, I recommend using `6.0.0` where we stopped shipping polyfills which seems to be the problem. You should be okay, because angular already handles polyfills.

**Comment by gigcompany** [comment]
> Can you try to do a clean install? If it still doesn't work, I recommend using `6.0.0` where we stopped shipping polyfills which seems to be the problem. You should be okay, because angular already handles polyfills.

I tried upgrading to 6.0.0. This error and other compile time errors were gone. But I started to get other runtime errors that I think are because other dependencies are not compatible like angularfire2. Looks like I will have to do a full upgrade of the app to the latest versions to get all of this seamlessly working.
