### ISSUE TITLE
Analytics is not a function

### ISSUE THREAD

**Issue by aakashrshah** [firebase/firebase-js-sdk#2414]
### [REQUIRED] Describe your environment

  * Operating System version: macOS v10.14.3
  * Browser version: Google Chrome v78.0.3904 
  * Firebase SDK version:  firebase@7.5.0 
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Describe the problem

The firebase authentication is still not working in version 7.5.0. Linked Issue #2213

**Comment by rommelpe** [comment]
Hi @aakashrshah, that's a bit unusual, not sure what I'm missing here but seems that I can't replicate this on my end, could you share a [mcve](https://stackoverflow.com/help/minimal-reproducible-example) so we can look into it further? What specific issue you encountered in Auth? Thanks.
