### ISSUE TITLE
TypeError: Object(...) is not a function when updating to v7.17.0 from v7.16.1

### ISSUE THREAD

**Issue by twebber90** [firebase/firebase-js-sdk#3469]
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS Mojave 10.14.6 (18G6020)
  * Browser version: Google Chrome 84.0.4147.89
  * Firebase SDK version: 7.17.0
  * Firebase Product: initializing, remote config, analytics

#### Steps to reproduce:
Happens when the application attempts to initialize with `firebase.initializeApp`

Renovate auto-merged a version bump from 7.16.1 to 7.17.0 and this error started occurring. Everything was working before the version bump 👍 

#### Relevant Code:

https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
firebase.initializeApp(require('path-to-config'));

const analytics = firebase.analytics(); // stack trace points to this being the failure
```

#### Stack trace of error running locally (same error occurs in production)
<img width="950" alt="Screen Shot 2020-07-23 at 8 26 13 PM" src="https://user-images.githubusercontent.com/54541871/88353592-bc01b780-cd23-11ea-891f-889ee1071888.png">

**Comment by hsubox76** [comment]
Sorry! I think this is caused by us not publishing the `@firebase/util` package which has changes needed to go along with the analytics change. I will try to get that package published quickly.

In the meantime, please roll back if you can and sorry for the error.

**Comment by twebber90** [comment]
No problem. Already did to verify this was the culprit 👍 thanks for the speedy response!

**Comment by hsubox76** [comment]
Just published 7.17.1 which includes the missing package. The release notes will be a little delayed.

**Comment by pfic** [comment]
Thanks for publishing the update! 

For anyone else that is still having the error after upgrading to 7.17.1, I also had to delete the node_modules and reinstall dependencies. Worked like a charm after that.

**Comment by hsubox76** [comment]
1) What was the latest version that works for you before it broke? Did 7.16.1 work?
2) Have you tried removing your yarn.lock or package-lock.json file before reinstalling?
