### ISSUE TITLE
firebase.analytics is not a function

### ISSUE THREAD

**Issue by goleary** [firebase/firebase-js-sdk#2213]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 1803
  * Browser version: chrome Version 77.0.3865.90 (Official Build) (64-bit)
  * Firebase SDK version: 7.0.0
  * Firebase Product: analytics

#### Steps to reproduce:
trying to use firebase (google) analytics for webapps as described [here](https://firebase.google.com/docs/analytics/get-started#firebase-gtag)

#### Relevant Code:

Tried to repro on stackblitz but it doesn't seem to work with firebase 7.0.0

```javascript
import * as firebase from "firebase";
firebase.initializeApp({...});
const analytics = firebase.analytics();
```

**Comment by goleary** [comment]
oddly enough after updating to 7.0.0 the analytics folder appears to missing from the package:
![image](https://user-images.githubusercontent.com/16123225/65914773-de86a680-e386-11e9-90cb-ce66ccdb5648.png)

**Comment by Feiyang1** [comment]
Thanks for reporting it! I made a quick fix and linked the PR here.
As a workaround (also the best practice), please import Firebase SDKs individually:
```
import * as firebase from 'firebase/app';
import 'firebase/analytics';
import 'firebase/auth'
...
```

**Comment by Feiyang1** [comment]
It has been fixed in `firebase@7.1.0`

**Comment by goleary** [comment]
thanks!
