### ISSUE TITLE
Firestore enablePersistence Exception "is not a function"

### ISSUE THREAD

**Issue by RaheutRahwana** [firebase/firebase-js-sdk#4274]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 16.04
  * Browser version: Firefox 85.0b5 (64-bit)
  * Firebase SDK version: 8.2.2
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
Offline persistence throws the exception "e is not a function." I realized this after updating to version 8.2.1 and also to 8.2.2. Previously I used version 8.1.1. After I explored further, this issue actually started in version 8.1.2.

#### Steps to reproduce:
1. Add Firebase SDKs and initialize Firebase from hosting URLs. https://firebase.google.com/docs/web/setup#from-hosting-urls
2. Configure offline persistence. https://firebase.google.com/docs/firestore/manage-data/enable-offline#web

#### Relevant Code:
```html
<script defer src="/__/firebase/8.2.2/firebase-app.js"></script>
<script defer src="/__/firebase/8.2.2/firebase-firestore.js"></script>
<script defer src="/__/firebase/init.js"></script>
```

```javascript
firebase.firestore().enablePersistence().catch(console.error);
```

**Comment by hsubox76** [comment]
Can we see more of the code, like how you're importing and initializing Firebase? Also, did this code work previously and only break in 8.2.2 or is it new code?

**Comment by RaheutRahwana** [comment]
> Can we see more of the code, like how you're importing and initializing Firebase? Also, did this code work previously and only break in 8.2.2 or is it new code?

I've updated it. Please review. Thanks!

**Comment by hsubox76** [comment]
I could not reproduce the error based on the info so far. I created an `index.html` file containing only this:

```
<!DOCTYPE html>
<html>
  <head>
    <script defer src="/__/firebase/8.2.2/firebase-app.js"></script>
    <script defer src="/__/firebase/8.2.2/firebase-firestore.js"></script>
    <script defer src="/__/firebase/init.js"></script>
  </head>
  <body>
    <p>test</p>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        firebase.firestore().enablePersistence().catch(console.error);
      });
    </script>
  </body>
</html>
```

and deployed it to Firebase hosting, and did not see any errors. Is there anything else in your file that might be throwing this error? Is the debugger definitely pointing at this line as the one causing the error?

**Comment by RaheutRahwana** [comment]
I tried it on localhost. It turns out that this issue only occurs in browsers version: `Firefox 85.0b5 (64-bit)`. Whereas in the `browser version Chromium 87.0.4280.66` everything is fine. Any suggestion?

**Comment by RaheutRahwana** [comment]
Can I have your URL? I want to try it from here. Thank you.

**Comment by hsubox76** [comment]
This is my test project so I can't guarantee the url will always point to this test page but I don't often deploy new tests to hosting so it probably won't change any time soon. https://chholland-test.web.app/

**Comment by RaheutRahwana** [comment]
Thank you for sharing the URL. I recorded a video of him. The first browser was Firefox, where the error occurred. While the second is Chromium where everything is okay. Any suggestion?

https://youtu.be/2pH7CNvy0lo

**Comment by hsubox76** [comment]
I can't reproduce it in the latest version of Firefox. The version you listed seems to be a beta version of Firefox. Do you still have the problem if you use the stable version?

For what it's worth I also tried the current Firefox beta (85.0b7) and did not see the error, but I have only tried on Mac and not Linux, and also this is a slightly newer beta version than yours (b5).

**Comment by RaheutRahwana** [comment]
If so, I consider this my local issue. I close it then. Thank you.
