### ISSUE TITLE
error app.auth is not a function after upgrading to v8.3.0

### ISSUE THREAD

**Issue by lc-tanishaverma** [firebase/firebase-js-sdk#4621]
### Describe your environment

  * Operating System version: MacOS Big Sur
  * Browser version: Google Chrome 88.0.4324.192
  * Firebase SDK version: 8.3.0
  * Firebase Product: auth (auth, database, storage, etc)

### Describe the problem
Importing default firebase app project from a shared library causes type error `app.auth() is not a function` after upgrading to v8.3.0

#### Steps to reproduce:

  1. Create firebase default app object in a react library.
  2. Update firebase version to 8.3.0.
  3. Import above created object in a different react project.
  
#### Relevant Code:

```javascript
// In shared library
  import firebase from 'firebase/app'
  require('firebase/auth')

  const app = firebase.initializeApp(config)
  export const appAuth = app.auth()
// In project
 import appAuth from 'shared-library'
```

**Comment by Feiyang1** [comment]
I can't reproduce it. I also can't think of any change in 8.3.0 that could cause this error.

I do notice that you are trying to import `appAuth` as a default import while it should be a named import - `import { appAuth } from 'shared-library'`. Is it a typo?

I also notice that you are mixing esm import and `require('firebase/auth')`. I don't think it matters with regards to typings, but maybe try `import 'firebase/auth'` which is also a good practice.

**Comment by lc-tanishaverma** [comment]
Yes sorry that was a typo but the error happens while creating the const on the line `export const appAuth = app.auth()`.
I tried with `import 'firebase/auth` instead of `require('firebase/auth')` and encountered the same error.
The issue reproducible even if the firebase app object is created within the app and not shared library.

After logging the firebase object which is imported using `import firebase from 'firebase/app'` I noticed that the auth function is missing from the object which can be seen in version firebase **v8.2.10.
Please see screenshots attached :
<img width="706" alt="Screen Shot 2021-03-15 at 10 27 05 AM" src="https://user-images.githubusercontent.com/51184192/111085210-387b2c00-857b-11eb-9c70-462432f3a6b8.png">
<img width="713" alt="Screen Shot 2021-03-15 at 10 31 11 AM" src="https://user-images.githubusercontent.com/51184192/111085213-3b761c80-857b-11eb-90a9-3168b2f33fbb.png">

**.

**Comment by Feiyang1** [comment]
Weird. `auth` should be patched onto the `firebase` object by `import 'firebase/auth'`. 
Your snippet looks correct (also I assume the same code works with `v8.2.10`), but is it possible you are doing `const appAuth = app.auth()` before `import 'firebase/auth'` ?

I tried 8.3.0 again and it still works for me. Would you mind creating/sharing a minimal repro that I can play with?

**Comment by lc-tanishaverma** [comment]
Yes the `firebase/auth` is being imported before `const appAuth = app.auth()`.

After investigating I found out that two dependencies in our app are using different versions of firebase.
Dependency A has dependency of firebase `v8.2.9`.
Dependency B has dependency of firebase `v8.3.0`.

Issue gets resolved by doing one of the actions:
1. Getting rid off either of the dependencies.
2. Adding firebase v8.3.0 as a dependency in the app. 

This is not an issue when dependency A uses v8.2.9 and dependency B uses v8.2.10.

**Comment by looptheloop88** [comment]
Hi @lc-tanishaverma, I wasn't able to replicate this issue as well using the JS SDK version 8.3.0. As @Feiyang1 said, `auth` should be patched to the `firebase` object by `import 'firebase/auth'` or `require("firebase/auth")`.

```
{
  __esModule: true,
  initializeApp: [Function: initializeApp],
  app: [Function: app] { App: [Function: FirebaseAppImpl] },
  registerVersion: [Function: registerVersion],
  setLogLevel: [Function: setLogLevel],
  onLog: [Function: onLog],
  apps: [Getter],
  SDK_VERSION: '8.3.0',
  INTERNAL: {
    registerComponent: [Function: registerComponent],
    removeApp: [Function: removeApp],
    components: Map(7) {
      'platform-logger' => [Component],
      'fire-core-node-version' => [Component],
      'fire-js-version' => [Component],
      'firebase-app-version' => [Component],
      'auth' => [Object],
      'auth-internal' => [Object],
      'fire-auth-version' => [Component]
    },
    useAsService: [Function: useAsService],
    createFirebaseNamespace: [Function: createFirebaseNamespace],
    extendNamespace: [Function: extendNamespace],
    createSubscribe: [Function: createSubscribe],
    ErrorFactory: [Function: ErrorFactory],
    deepExtend: [Function: deepExtend],
    node: {
      localStorage: Storage {},
      sessionStorage: Storage {},
      XMLHttpRequest: [Function (anonymous)]
    }
  },
  default: [Circular *1],
  auth: [Function: serviceNamespace] {
    ActionCodeInfo: { Operation: [Object] },
    Auth: [Function: En] { ab: [Uc], Persistence: [Object] },
    AuthCredential: [Function: Bg] { fromJSON: [Function: d] },
    Error: [Function: t] { ab: {} },
    EmailAuthProvider: [Function: d] {
      PROVIDER_ID: 'password',
      EMAIL_LINK_SIGN_IN_METHOD: 'emailLink',
      EMAIL_PASSWORD_SIGN_IN_METHOD: 'password',
      credential: [Function: d],
      credentialWithLink: [Function: d]
    },
    FacebookAuthProvider: [Function: d] {
      ab: [Ng],
      PROVIDER_ID: 'facebook.com',
      FACEBOOK_SIGN_IN_METHOD: 'facebook.com',
      credential: [Function: d]
    },
    GithubAuthProvider: [Function: d] {
      ab: [Ng],
      PROVIDER_ID: 'github.com',
      GITHUB_SIGN_IN_METHOD: 'github.com',
      credential: [Function: d]
    },
    GoogleAuthProvider: [Function: d] {
      ab: [Ng],
      PROVIDER_ID: 'google.com',
      GOOGLE_SIGN_IN_METHOD: 'google.com',
      credential: [Function: d]
    },
    TwitterAuthProvider: [Function: d] {
      ab: [Object],
      PROVIDER_ID: 'twitter.com',
      TWITTER_SIGN_IN_METHOD: 'twitter.com',
      credential: [Function: d]
    },
    OAuthProvider: [Function: d] { ab: [Object] },
    SAMLAuthProvider: [Function: d] { ab: [Object] },
    PhoneAuthProvider: [Function: d] {
      PROVIDER_ID: 'phone',
      PHONE_SIGN_IN_METHOD: 'phone',
      credential: [Function: d]
    },
    RecaptchaVerifier: [Function: d] { ab: [Object] },
    ActionCodeURL: [Function: d] { parseLink: [Function: d] },
    PhoneMultiFactorGenerator: [Function: d] { FACTOR_ID: 'phone', assertion: [Function: d] }
  },
  User: [Function: Im] {
    ab: Uc {
      constructor: [Function],
      closure_listenable_859155: true,
      addEventListener: [Function (anonymous)],
      removeEventListener: [Function (anonymous)],
      dispatchEvent: [Function (anonymous)],
      Da: [Function (anonymous)]
    }
  }
```

Could you please create or share a sample project that we can use to replicate this issue?

**Comment by lc-tanishaverma** [comment]
Auth is missing only when you use two libraries in an app have a different firebase version and one of them being at v8.3.0.
We were able to resolve by reducing one dependency from the app. You may close the issue since create this scenario to reproduce this issue will involve creating three apps and then publishing two of them to be able to be used by the third one.

**Comment by looptheloop88** [comment]
Thanks. I will close this issue now.
