### ISSUE TITLE
Can I provide a custom persistence implementation for auth in node?

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-js-sdk#1874]
I need to persist the user across sessions in node - is there to do this?

**Comment by bojeil-google** [comment]
That is not currently available. We will consider it in our [modularization](https://github.com/firebase/firebase-js-sdk/issues/332) efforts.

**Comment by nbransby** [comment]
Can you suggest a workaround? Maybe use onIdTokenChanged to save the user and updateCurrentUser on startup to restore? Problem with that is deserializing the user with the correct prototype

**Comment by JakeHedman** [comment]
Bit late to the party, but this workaround worked for me:

Save user:
```js
const userJson = JSON.stringify(currentUser.toJSON())
// Write userJson to disk
```

Load user:
```js
// Read userJson from disk
const userData = JSON.parse(userJson)
const user = firebase.User(userData, userData.stsTokenManager, userData)
firebase.auth().updateCurrentUser(user)
```

**Comment by dfernandezm** [comment]
> Bit late to the party, but this workaround worked for me:
> 
> Save user:
> 
> ```js
> const userJson = JSON.stringify(currentUser.toJSON())
> // Write userJson to disk
> ```
> 
> Load user:
> 
> ```js
> // Read userJson from disk
> const userData = JSON.parse(userJson)
> const user = new firebase.User(userData, userData.stsTokenManager, userData)
> firebase.auth().updateCurrentUser(user)
> ```

@JakeHedman I would love to implement this, but at least in my Typescript setup I get the following:

```
const user = new firebase.User(userData, userData.stsTokenManager, userData);
```

```
Property 'User' does not exist on type 'typeof firebase'.ts(2339)
```

Seems like I can reference the type but not instantiate it. I am using:

```
"firebase": "^7.14.3",
"firebase-admin": "^8.12.1",
```

Any workarounds on how to instantiate `firebase.User` that way with Typescript?

**Comment by billybraga** [comment]
> Bit late to the party, but this workaround worked for me:
> 
> Save user:
> 
> ```js
> const userJson = JSON.stringify(currentUser.toJSON())
> // Write userJson to disk
> ```
> 
> Load user:
> 
> ```js
> // Read userJson from disk
> const userData = JSON.parse(userJson)
> const user = new firebase.User(userData, userData.stsTokenManager, userData)
> firebase.auth().updateCurrentUser(user)
> ```

Could this be documented as a public API so we can rely on it not changing in the future?

**Comment by tonyxiao** [comment]
Seems to break as of firebase version `7.21.0`. Works on firebase version `7.19.1`

**Comment by malcolmdeck** [comment]
Hey folks, 

I've filed b/169069711 to track this feature request internally. The modularization effort is ongoing - once we complete that we should be in a place where we can consider this feature request.

Hope that helps!
~Malcolm

**Comment by KuhlTime** [comment]
I have the same issue as _dfernandezm_. I am using Typescript and can't instantiate a new `firebase.User` instance. 

> Property 'User' does not exist on type 'typeof firebase'.ts(2339)

When changing the typescript file to a js file the issue is gone, but I am presented with a new one:

```
TypeError: Cannot read property 'idToken' of undefined
```

<details>
  <summary>Stacktrace</summary>
  <pre><code>(node:29312) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'idToken' of undefined
    at new Im (/home/pi/luftgut-core/node_modules/@firebase/auth/dist/src/authuser.js:198:7)
    at /home/pi/luftgut-core/src/firebase/authStateChange.js:17:22
    at Generator.next (<anonymous>)
    at /home/pi/luftgut-core/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/pi/luftgut-core/node_modules/tslib/tslib.js:111:16)
    at Object.index_1.auth.onAuthStateChanged [as next] (/home/pi/luftgut-core/src/firebase/authStateChange.js:10:38)
    at /home/pi/luftgut-core/node_modules/@firebase/util/src/subscribe.ts:104:16
    at /home/pi/luftgut-core/node_modules/@firebase/util/src/subscribe.ts:233:11
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
</code></pre>
</details>

I tried both the latest `8.2.0` release as well as the `7.19.1` release suggested by _tonyxiao_.

**Comment by mrcrowl** [comment]
> Any workarounds on how to instantiate `firebase.User` that way with Typescript?

I just hit this in TypeScript too. One workaround is:

```typescript
// Read userJson from disk
const userData = JSON.parse(userJson)
const user: firebase.User = new (firebase as any).User(userData, userData.stsTokenManager, userData)
firebase.auth().updateCurrentUser(user)
```

**Comment by smashah** [comment]
For people using the new packages in TS:

```ts
import { getAuth, signInWithCustomToken, User } from "@firebase/auth";
import { UserImpl } from '@firebase/auth/internal';

...

const user : User = UserImpl._fromJSON(getAuth() as any, userData)
await getAuth().updateCurrentUser(user);
```
Just for reference, the session logs out in 55 minutes automatically

**Comment by d0gkiller87** [comment]
Dirty solution for version 9 (tested on 9.6.6):

It relies on the internal method `Auth._initializeWithPersistence` and `persistenceManager` to manually read/write the `inMemoryPersistence`. (this took me 5 hours reading the SDK's codebase and testing due to limited number of exports :/)

```javascript
import filesystem from 'fs';

import {
  getAuth,
  inMemoryPersistence,
  updateCurrentUser
} from 'firebase/auth';

let auth = getAuth();

async load_persistence() {
  const persistence = JSON.parse( filesystem.readFileSync( 'persistence.json' ) );
  if ( !persistence ) return;

  // _initializeWithPersistence( persistenceHierarchy, popupRedirectResolver ) creates a `persistenceManager`
  await auth._initializeWithPersistence( inMemoryPersistence, null );
  // attach the persistence storage that we loaded from `persistence.json` 
  auth.persistenceManager.persistence.storage = persistence;
  // "sync" the authentication status across the whole auth module
  await updateCurrentUser( auth, await auth.persistenceManager.getCurrentUser() );
}

save_persistence() {
  filesystem.writeFileSync( 'persistence.json', JSON.stringify( auth.persistenceManager.persistence.storage ) );
}

async main() {
  await load_persistence();
  // (after signInWithEmailAndPassword, signOut, etc...)
  save_persistence();
}
```

**Comment by vmutafov** [comment]
As I've hit the need for having persistent auth storage for a CLI I'm building, I have written a simple npm library for creating a file-backed persistence: https://www.npmjs.com/package/@vmutafov/firebase-auth-node-persistence

Using it pretty much boils down to:
```TypeScript
import { getApp } from "firebase/app";
import { initializeAuth } from "firebase/auth";
import { createNodeFilePersistence } from "@vmutafov/firebase-auth-node-persistence";
import { resolve } from "node:path";
import { cwd } from "node:process";

const app = getApp();

const nodeFilePersistence = createNodeFilePersistence({
    filePath: resolve(cwd(), '.authrc')
});

const auth = initializeAuth(app, {
    persistence: [nodeFilePersistence]
});
```

It's still something experimental and not very well tested but at least works for my use case and I hope it would help others too

**Comment by SusyVenta** [comment]
> Dirty solution for version 9 (tested on 9.6.6):
> 
> It relies on the internal method `Auth._initializeWithPersistence` and `persistenceManager` to manually read/write the `inMemoryPersistence`. (this took me 5 hours reading the SDK's codebase and testing due to limited number of exports :/)
> 
> ```js
> import filesystem from 'fs';
> 
> import {
>   getAuth,
>   inMemoryPersistence,
>   updateCurrentUser
> } from 'firebase/auth';
> 
> let auth = getAuth();
> 
> async load_persistence() {
>   const persistence = JSON.parse( filesystem.readFileSync( 'persistence.json' ) );
>   if ( !persistence ) return;
> 
>   // _initializeWithPersistence( persistenceHierarchy, popupRedirectResolver ) creates a `persistenceManager`
>   await auth._initializeWithPersistence( inMemoryPersistence, null );
>   // attach the persistence storage that we loaded from `persistence.json` 
>   auth.persistenceManager.persistence.storage = persistence;
>   // "sync" the authentication status across the whole auth module
>   await updateCurrentUser( auth, await auth.persistenceManager.getCurrentUser() );
> }
> 
> save_persistence() {
>   filesystem.writeFileSync( 'persistence.json', JSON.stringify( auth.persistenceManager.persistence.storage ) );
> }
> 
> async main() {
>   await load_persistence();
>   // (after signInWithEmailAndPassword, signOut, etc...)
>   save_persistence();
> }
> ```

Where do you recommend saving the file in production? And is it enough to save it once or shoudl it be one file per each user?

**Comment by d0gkiller87** [comment]
> Where do you recommend saving the file in production?

It's generally not recommended to use an internal structure in production, although I understand that you may have limited options.

The choice of path is entirely up to you, for example you could save it to where you put user's data:
- If it's an installable app, you could save it under `%appdata%/xxx/` on Windows or `~/.config/xxx` on Linux
- If it's a portable app, you could save it in the same directory as the program itself
> Is it enough to save it once or shoudl it be one file per each user?

The structure is specific to each user, but you have the flexibility to implement your own user management loader/saver. The structure `auth.persistenceManager.persistence.storage` is JSON friendly, you could make any modifications you need.

For example, unless you have security concerns, you could save multiple user's session in a single file like this:
```js
{
  "user1@gmail.com": /* user1's auth.persistenceManager.persistence.storage */,
  "user2@gmail.com": /* user2's auth.persistenceManager.persistence.storage */,
  ...
}
```
