### ISSUE TITLE
app.database() is not a function

### ISSUE THREAD

**Issue by EECOLOR** [firebase/firebase-js-sdk#3376]
### Describe your environment

  * Operating System version: Ubuntu 20.04 LTS
  * Node version: v10.20.1
  * Firebase SDK version: 7.14.3+
  * Firebase Product: database

### Describe the problem

After creating an app the `database` function does not exist. This is a regression, it worked in 7.14.2.

#### Steps to reproduce:

```js
const app = firebase.initializeApp({
  databaseURL: `ws://localhost:5000`,
})

const db = app.database()
```

Error:
```js
TypeError: app.database is not a function
```

#### Relevant Code:

You can use `firebase-server` to start a local server.

Problem can be seen by running `yarn test` on a checkout of https://github.com/kaliberjs/firebase-queue

**Comment by hsubox76** [comment]
I was able to reproduce it in that specific repo. The cause seems to be the `firebase-server` dependency, which itself depends on `firebase@>= 5.0.0`. The repo starts with firebase@7.14.2, which, as stated above, works fine. Upgrading to firebase@7.14.3 specifically causes two versions of firebase to be installed: 7.14.2 remains in yarn.lock because it meets `firebase-server`'s >= 5.0.0 requirement, and now 7.14.3 is added as an additional version. I think some kind of conflict between both of those causes this.

It seems like this can be fixed by deleting yarn.lock and running yarn install again.

**Comment by EECOLOR** [comment]
@hsubox76 Thank you very much for investigating! I wished I thought about that being the problem myself. Thanks again!
