### ISSUE TITLE
Error when upgrading from 7.8.2 to 7.9.0

### ISSUE THREAD

**Issue by tianhaoz95** [firebase/firebase-js-sdk#2655]
### Describe your environment

  * Operating System version: GitHub Actions ubuntu-latest
  * Browser version: headless
  * Firebase SDK version: 7.9.0
  * Firebase Product: core/firestore

### Describe the problem

The following error was thrown when upgrading firebase from `7.8.2` to `7.9.0` during jest tests with firebase emulator:

```bash
console.error node_modules/@firebase/firestore/node_modules/@firebase/logger/dist/index.cjs.js:94
    [2020-02-20T23:09:42.930Z]  @firebase/firestore: Firestore (7.8.1): FIRESTORE (7.8.1) INTERNAL ASSERTION FAILED: AsyncQueue is already failed: TypeError: __PRIVATE_protoLoader.HP is not a function
        at __PRIVATE_loadProtos (/home/runner/work/iwfp/iwfp/iwfpapi/functions/node_modules/@firebase/firestore/src/platform_node/load_protos.ts:48:29)
        at t.platform [as SE] (/home/runner/work/iwfp/iwfp/iwfpapi/functions/node_modules/@firebase/firestore/src/platform_node/node_platform.ts:47:20)
        at t._this [as bE] (/home/runner/work/iwfp/iwfp/iwfpapi/functions/node_modules/@firebase/firestore/src/core/firestore_client.ts:397:17)
        at /home/runner/work/iwfp/iwfp/iwfpapi/functions/node_modules/@firebase/firestore/src/core/firestore_client.ts:185:31
        at process._tickCallback (internal/process/next_tick.js:68:7)


TypeError: __PRIVATE_protoLoader.HP is not a function

      at __PRIVATE_loadProtos (node_modules/@firebase/firestore/src/platform_node/load_protos.ts:48:29)
      at t.platform [as SE] (node_modules/@firebase/firestore/src/platform_node/node_platform.ts:47:20)
      at t._this [as bE] (node_modules/@firebase/firestore/src/core/firestore_client.ts:397:17)
      at node_modules/@firebase/firestore/src/core/firestore_client.ts:185:31
```

here is a link to the GitHub Actions result page: https://github.com/tianhaoz95/iwfp/pull/330/checks?check_run_id=459036204

#### Steps to reproduce:
1. clone the repository https://github.com/tianhaoz95/iwfp
2. `cd iwfpapi/functions`
3. `npm install && npm run e2e`
4. see it works
5. `npm install firebase --upgrade`
6. `npm run e2e`
7. see it breaks with the error message in the last section.

**Comment by schmidt-sebastian** [comment]
@tianhaoz95 We will get this fixed shortly. For now, can you stay on 7.8.2?

**Comment by alexvandervegt** [comment]
I have the same issue

**Comment by tianhaoz95** [comment]
@alexvandervegt so it seems to be a indirect dependency version mismatch. It should be an easy fix for the firebase team. I am guessing skipping 7.9.0 is not a big deal.

**Comment by schmidt-sebastian** [comment]
We are in the process of staging a new release that should fix this issue.

**Comment by alexvandervegt** [comment]
Awesome, thanks!

**Comment by schmidt-sebastian** [comment]
7.9.1 is published.

**Comment by tianhaoz95** [comment]
Great! verified that upgrading to `7.9.1` works! Thanks for fixing the issue!

**Comment by alexvandervegt** [comment]
Yes me2
