### ISSUE TITLE
Error when initializing an SDK component (is not a function)

### ISSUE THREAD

**Issue by alexeigs** [firebase/firebase-js-sdk#1493]
* Firebase SDK version: 5.8.0
  * Firebase Product: firestore

The error only started to occur after the update from 5.7.3 to 5.8.0:

`Uncaught TypeError: app.firestore is not a function
    at eval (firebaseConfig.ts)
    at Module../src/firebaseConfig.ts`

caused by the last line of the following snipped (part of my firebaseConfig.ts file):

```
import * as firebase from 'firebase/app'
import 'firebase/firestore'
import 'firebase/auth'
import 'firebase/functions'

// Initialize Firebase
const config = {
    apiKey: 'xxx',
    authDomain: 'xxx',
    databaseURL: 'xxx',
    projectId: 'xxx',
    storageBucket: 'xxx',
    messagingSenderId: 'xxx',
}

const app = firebase.initializeApp(config)

const db = app.firestore()
```

The same happens for `app.auth()` and possibly the other SDK components. `firebase.firestore()` instead of `app` leads to the same error.

**Comment by alexeigs** [comment]
@mpigsley I deleted the firebase-module completely after the update and reinstalled it which worked for me. I guess package-lock.json caused some troubles.
