### ISSUE TITLE
fetch is not a function while using firebase storage in node.js

### ISSUE THREAD

**Issue by shahkeyur** [firebase/firebase-js-sdk#5298]
Firebase version: 8.9.1
Node: 14.17.0
Service: Storage

I am trying to upload a file using firebase storage using node on electron. It is working on firebase 8.8.1, I tried updating with new release today, and it's broken. 

Nothing was changed in code. Here's the piece of code I am using. 
```
const userStorageRef = await firebase
                      .storage("my-bucket')
                      .ref(`abc/345`);

const monitorUpload = userStorageRef.put(
  exportZip.toBuffer(),
);
```

```
Uncaught Exception: 
TypeError: fetch is not a function
    at FetchConnection.send (webpack://my-app/./node_modules/@firebase/storage/dist/index.node.cjs.js?:558:16)
    at doTheRequest (webpack://my-app/./node_modules/@firebase/storage/dist/index.node.cjs.js?:1032:18)
    at Timeout.eval [as _onTimeout] (webpack://my-app/./node_modules/@firebase/storage/dist/index.node.cjs.js?:816:13)
    at listOnTimeout (internal/timers.js:554:17)        
    at processTimers (internal/timers.js:497:7)
```

**Comment by schmidt-sebastian** [comment]
@shahkeyur Sorry to hear that. We actually did not change much for Storage between 8.8.1 and 8.9.1. The bigger change was in 8.8.0, which added Node support, which looks like it is causing your problem. Can you configure Webpack to use the browser build instead of the Node build? You should not be including "index.node.cjs.js".

**Comment by shahkeyur** [comment]
@schmidt-sebastian Thanks for the response. I think it already does create the browser build. My webpack resolve field looks like this. My understanding is adding mainFields should do that.

However, I am not able to understand why it would work with 8.8.0, 8.8.1 and not in 8.9.1. It works well with the 8.8.*. All I am just doing is switching the firebase versions from npm, and nothing else. 

![image](https://user-images.githubusercontent.com/34612659/129421275-e9895c71-e13c-4f66-bd86-5958dcb0348a.png)

**Comment by shahkeyur** [comment]
Actually, it worked this time, I guess the issue was package-lock. I clean-installed and it worked this time. 

Thanks!
