### ISSUE TITLE
Getting firebase.auth is not a function in 7.20+

### ISSUE THREAD

**Issue by mkonikov** [firebase/firebase-js-sdk#3828]
* Operating System version: macOS Catalina
  * Browser version: Chrome
  * Firebase SDK version: 7.19.1 & 7.20.0
  * Firebase Product: Firestore

### Describe the problem
`firebase.auth` is returning undefined as of 7.20.0 - but worked in 7.19.1 and earlier.

#### Steps to reproduce:
Bump from 7.19.1 to 7.20.0 
#### Relevant Code:
Server side code runs like this
```javascript
const firebase = require('firebase/app');
// Required for side-effects
require('firebase/firestore');
require('firebase/auth');
console.log('firebase.auth', typeof firebase.auth) // Undefined
```
Previously, on `7.19.1` I would get `function` in the console.log and my code further down (`await firebase.auth()`) would work just fine. 

Now it logs `undefined` and get an error 
```
TypeError: firebase.auth is not a function
```

**Comment by hsubox76** [comment]
I've tried this with a fresh install and am not getting any errors.

Similar errors seem to have been fixed in the past after a clean install (delete `node_modules`, delete `yarn.lock` or `package-lock.json`, reinstall with npm or yarn). Can you try that first?

**Comment by KenCorbettJr** [comment]
I had this same issue just this morning and clearing things out and doing a fresh clean install got things working again.

> I've tried this with a fresh install and am not getting any errors.
> 
> Similar errors seem to have been fixed in the past after a clean install (delete `node_modules`, delete `yarn.lock` or `package-lock.json`, reinstall with npm or yarn). Can you try that first?

**Comment by mkonikov** [comment]
I got it to work after a while. Again no clue why but thanks all!
