### ISSUE TITLE
Check isNewUser not showing in v9 sdk

### ISSUE THREAD

**Issue by rhythmbhiwani** [firebase/firebase-js-sdk#5393]
### Environment

  * Operating System version: ```Windows 10```
  * Browser version: ```v92```
  * Firebase SDK version: ```9.0.0```
  * Firebase Product: ```auth```

#### Steps to reproduce:

On the version 8, is was easy to check if the user is new or already registerd was easy. But since I upgraded to v9, I'm not able to find the property to check this. I tried console.log the ```firebaseUser``` object (Which is type of UserCredential). It showed this property under ```_tokenResponse``` , but then typescript shows error that ```Property '_tokenResponse' does not exist on type 'UserCredential'```

#### Relevant Code:

Previously on v8
```javascript
if (firebseUser.additionalUserInfo.isNewUser) {
// Do something for new user
}
```

Please can someone check and help how can I do it properly on the v9
